version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: medium
    steps:
      - checkout
      - run: |
             chmod +x deploy.sh
             
             
# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main
